import turtle
pen =turtle.Turtle()
turtle.fillcolor('red')
turtle.title('Rectangle')
pen.goto(0,0)
for a in range(2):
    turtle.begin_fill()
    pen.forward(160)
    pen.right(90)
    pen.forward(100)
    pen.right(90)
turtle.end_fill()
pen.up()
pen.goto(50,50)
pen.down()
for a in range(2):
    pen.forward(160)
    pen.right(90)
    pen.forward(100)
    pen.right(90)
pen.goto(0,0)
pen.up()
pen.goto(160,0)
pen.down()
pen.goto(210,50)
pen.up()
pen.goto(210,-50)
pen.down()
pen.goto(160,-100)
pen.up()
pen.goto(0,-100)
pen.down()
pen.goto(50,-50)
turtle.end_fill()
turtle.done()