import turtle
screen=turtle.Turtle()
turtle.title('Redmi Note 5 Pro')
#body
screen.goto(0,0)
for a in range(2):
    screen.forward(160)
    screen.right(90)
    screen.forward(300)
    screen.right(90)
screen.up()
#Header Camera and speaker
screen.goto(0,-20)
screen.down()
screen.forward(160)
screen.up()
screen.goto(30,-12)
screen.down()
screen.circle(3)
screen.up()
screen.goto(80,-8)
screen.down()
for b in range(2):
    screen.forward(15)
    screen.right(90)
    screen.forward(4)
    screen.right(90)
screen.up()
screen.goto(0,-280)
screen.down()
screen.forward(160)
screen.up()
screen.goto(18,-287)
screen.down()
screen.right(90)
for c in range(3):
    screen.forward(7)
    screen.right(120)
screen.up()
screen.goto(75,-290)
screen.down()
screen.circle(3)
screen.up()
screen.goto(140,-287)
screen.down()
for d in range(4):
    screen.forward(5)
    screen.right(90)
screen.up()
screen.goto(80,-130)
screen.down()
screen.write("Nothing\nIts Done")
screen.up()
screen.goto(70,70)
turtle.done()